name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Astron Collection.
title: "[Bug]: "
labels: [bug, needs-triage]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete the form below so we can fix it as quickly as possible. 🙏

  - type: input
    id: affected-component
    attributes:
      label: Which app/module is affected?
      placeholder: ex. astron-player, astron-modmail, shared-api
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I try to use the /play command, it returns...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste logs, errors, or screenshots to help us debug.
      render: shell
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Node.js version, Discord.js version, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I’ve double-checked for duplicate issues.
          required: true
        - label: I’ve included all relevant details and logs.
          required: true